# Site settings
title: eibay coding adventures
header-img: img/home-bg.png
email: eibayan@gmail.com
copyright_name: eibay
description: > # this means to ignore newlines until "baseurl:"
  My journey as a programmer lives here
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  eibay
learn_profile: eibay
email_username: eibayan@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
